from enum import Enum, auto


class LEXER_CONFIG_OPITONS(Enum):
    MAX_NUM_LENGTH = auto()
    MAX_IDENTIFIER_LENGTH = auto()


LEXER_CONFIG: dict[LEXER_CONFIG_OPITONS, int] = {
    LEXER_CONFIG_OPITONS.MAX_NUM_LENGTH: 30,
    LEXER_CONFIG_OPITONS.MAX_IDENTIFIER_LENGTH: 100,
}
